Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 20
  MaxPageSize: 1000
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 7811175yy  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: tenant
  TablePrefix: tenant
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30